site_name: My Docs
site_url: http://127.0.0.1:5500/
docs_dir: source
site_dir: docs
use_directory_urls: true

theme:
  name: material

nav:
  - Home: index.md
  - File1: file1.md  
  - File2: file2.md